### ISSUE TITLE
CHG move theia pod ClusterIP polling from rpc to seperate deployment

### ISSUE THREAD

**Issue by wabscale** [GusSand/Anubis#204]
# Overview

[This](https://github.com/GusSand/Anubis/blob/64d00e0f0ce2f3e1cb6ad8d139b24ffb7f4428a2/api/anubis/rpc/theia.py#L20) is the function that is called in an rpc-theia worker when someone clicks the button to launch a cloud ide. That function
does two main things. [It creates the Kubernetes resources](https://github.com/GusSand/Anubis/blob/64d00e0f0ce2f3e1cb6ad8d139b24ffb7f4428a2/api/anubis/rpc/theia.py#L96) (pod and possibly pvc), then it [polls for the pod to enter a running state](https://github.com/GusSand/Anubis/blob/64d00e0f0ce2f3e1cb6ad8d139b24ffb7f4428a2/api/anubis/rpc/theia.py#L114). The worker is held until this condition is met. We do this because we need to mark the session as active once the server starts,
and we need to record the pod ip address when it becomes available. 

Holding the worker has occasionally become a problem when under heavy load in the past (around midterms & finals). The 
worker is held for a maximum for 60 seconds. If the theia pod does not become active in that time, then the worker is released,
and the session is sort of in a wonked state. The user will just see a spinner on the website that wont end. They are sort
of shit out of luck at that point. The reaper job does check and fix these inconsistencies, but it is run every 5 minutes.

# Proposed Change

What I propose we do is move the poll & update section of this code to a separate deployment. We can check every few seconds
for pods that have come up, and record the necessary things for sessions. With this paradigm, the rpc workers can be released
as soon as they create the Kubernetes resources. The new deployment would then be checking every few seconds for
active sessions without ClusterIPs and try to match them to existing pods.

These changes will allow for potentially longer pod initialization time without timeouts breaking things. With the move to cloud,
there are a few situations that could require longer init times. The cluster could be actively scaling, so there is delay to provision
the new node from digital ocean, add it to the cluster, then pull the theia docker image from the registry.

# TODO

- [ ] Move polling logic to script under `api/jobs/`
  - [ ] Adjust the logic to run every few seconds
  - [ ] Update sessions in the database that lack ClusterIP
  - [ ] Update sessions in the database that have failed
- [ ] Create new k8s deployment under `k8s/chart/templates/` (maybe `ide-watcher.yaml`?)
  - [ ] Consider scaling and availability. If this deployment fails, ides will not be able to open.
  - [ ] Configure the service accounts
    - [ ] The `anubis-rpc` service account can be used as a template for this deployments's api permissions (only pod read & watch should be necessary)
