### ISSUE TITLE
CHG make assignment due date optionally hidden to students

### ISSUE THREAD

**Issue by wabscale** [GusSand/Anubis#221]
# Overview

Some classes may only want to use the Cloud IDE features of Anubis. For these cases, they will create a single assignment that is available throughout the entire semester. The red due date on the public assignment card is then not going to have meaning and lead to confusion.

# TODO

- [ ] Add `due_date_hidden` field to Assignment model
  - [ ] Generate migration
- [ ] Add switch to assignment admin card
- [ ] Add logic to handle hidden due dates to public assignment card
