### ISSUE TITLE
ADD a anubis-theia ping plugin to the ides for monitoring with ides are in use

### ISSUE THREAD

**Issue by wabscale** [GusSand/Anubis#237]
# Overview 

We have a problem where the majority of ides that are open do not get closed by the user. We need to add a plugin to the ide's that pings the backend every few minutes. With that we can keep track of which ides are actually open. We can then stop and cleanup ides that have not been active for a few minutes.

I actually planned doing this from the beginning, but did not ever get around to it. There is an unused column called [last_heartbeat](https://github.com/GusSand/Anubis/blob/aa961c57934b9a170800d10f6117a7a594d7f352/api/anubis/models/__init__.py#L684) which was suppose to be used for this.

# TODO

- [ ] Add a ping / heartbeat plugin to ides. It looks like [this is the place](https://theia-ide.org/docs/authoring_plugins) to follow how to setup theia plugins 
- [ ] Add something to [theia-proxy](https://github.com/GusSand/Anubis/blob/master/theia/proxy/index.js) to update the `last_heartbeat` field for a certain theia session. I started to write something like that [here](https://github.com/GusSand/Anubis/blob/aa961c57934b9a170800d10f6117a7a594d7f352/theia/proxy/index.js#L130) 
- [ ] Add something to [reaper job](https://github.com/GusSand/Anubis/blob/master/api/jobs/reaper.py) to check for inactive ides
  - [ ] Clean up inactive repo resources
